- README.md
This PR updates banner image in the README
> docs: Update banner image

- example/app/src/examples/SortableGrid/PlaygroundExample.tsx
- packages/react-native-sortables/src/hooks/useHaptics.ts
- packages/react-native-sortables/src/lib/react-native-haptic-feedback/index.ts
- packages/react-native-sortables/src/providers/shared/components/OrderUpdaterComponent.tsx
- packages/react-native-sortables/src/providers/utils/createProvider.tsx
- packages/react-native-sortables/src/utils/children.ts
- packages/react-native-sortables/src/utils/index.ts
- packages/react-native-sortables/src/utils/layout.ts
- packages/react-native-sortables/src/utils/logs.ts
> fix: Crash when haptic feedback is not installed in expo managed app

- example/app/src/components/layout/Description.tsx
- example/app/src/components/layout/Group.tsx
- example/app/src/components/layout/Section.tsx
- example/app/src/examples/SortableFlex/HorizontalAutoScrollExample.tsx
Just an example screen for horizontal sortable flex
https://github.com/user-attachments/assets/02115978-f4a2-45c9-8b16-fc23643a8a9d
> chore: Implement better horizontal autoscroll example for flex layout

- example/app/src/examples/SortableFlex/DataChangeExample.tsx
- example/app/src/examples/SortableFlex/DebugExample.tsx
- example/app/src/examples/SortableFlex/FlexLayoutExample.tsx
- example/app/src/examples/SortableGrid/DataChangeExample.tsx
- example/app/src/examples/SortableGrid/DebugExample.tsx
- example/app/src/examples/SortableGrid/DifferentSizeItems.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.web.ts
- packages/react-native-sortables/src/utils/props.ts
This PR fixes 3 issues described in the title noticed while testing apps on Android, iOS and web at the same time.
> fix: Web sortables resizing and drop animation on web, change to absolute layout on Android

- example/app/src/examples/SortableFlex/DragHandleExample.tsx
- example/app/src/examples/SortableFlex/index.ts
- example/app/src/examples/navigation/routes.ts
Adds a similar example to the one added previously only for the sortable grid.
> chore: Sortable flex drag handle example

- example/app/src/examples/SortableGrid/miscellaneous/StaggerAnimationExample.tsx
- packages/react-native-sortables/src/components/SortableFlex.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/constants/props.ts
- packages/react-native-sortables/src/types/props/shared.ts
This PR adds a possibility to enable sortable container overflow
> feat: Container overflow customization

- example/app/src/components/items/GridCard.tsx
- example/app/src/components/layout/Section.tsx
- example/app/src/examples/SortableFlex/features/AutoScrollExample.tsx
- example/app/src/examples/SortableFlex/features/HorizontalAutoScrollExample.tsx
- example/app/src/examples/SortableGrid/features/AutoScrollExample.tsx
- example/app/src/examples/SortableGrid/features/DragHandleExample.tsx
- example/app/src/examples/SortableGrid/features/HorizontalGridAutoScrollExample.tsx
- example/app/src/examples/SortableGrid/features/index.ts
- example/app/src/examples/navigation/routes.ts
- packages/react-native-sortables/src/components/SortableFlex.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/constants/props.ts
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/updates/common.ts
- packages/react-native-sortables/src/providers/layout/grid/updates/swap.ts
- packages/react-native-sortables/src/providers/layout/grid/utils/helpers.ts
- packages/react-native-sortables/src/providers/layout/grid/utils/layout.ts
- packages/react-native-sortables/src/types/layout/grid.ts
- packages/react-native-sortables/src/types/props/grid.ts
- packages/react-native-sortables/src/types/providers/layout.ts
- packages/react-native-sortables/src/utils/props.ts
This PR adds horizontal grid support with horizontal auto scroll.
https://github.com/user-attachments/assets/d137e8cc-b7c4-4375-9869-31908f7cfa22
> feat: Add horizontal direction support to the Sortable Grid

- example/app/src/examples/custom/CustomDropIndicator.tsx
- packages/docs/docs/grid/examples/drop-indicator.mdx
This PR updates example with custom drop indicator in docs to use correct properties.
> docs: Update custom drop indicator example in docs

- .eslintignore
- .eslintrc.cjs
- example/app/src/examples/navigation/ExamplesStackNavigator.tsx
- packages/react-native-sortables/src/components/shared/SortableHandle.tsx
- packages/react-native-sortables/src/components/shared/SortableLayer.tsx
- packages/react-native-sortables/src/components/shared/createSortableTouchable.tsx
- packages/react-native-sortables/src/index.ts
- packages/react-native-sortables/src/types/props/flex.ts
- packages/react-native-sortables/src/types/props/grid.ts
- packages/react-native-sortables/src/types/props/shared.ts
This PR adds TSDoc strings to all exposed APIs from the library.
> chore: Document exposed functions, types and components

- CONTRIBUTING.md
- README.md
This PR updates colors of badges and some information in the README file.
> docs: Update README.md

- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
This PR fixes active item portal provider implementation on web.
> fix: Active item portal provider on web

- example/app/src/examples/SortableFlex/features/CallbacksExample.tsx
- example/app/src/examples/SortableFlex/features/DataChangeExample.tsx
- example/app/src/examples/SortableGrid/features/CallbacksExample.tsx
- packages/react-native-sortables/src/components/SortableFlex.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/hooks/handlers/useDragEndHandler.ts
- packages/react-native-sortables/src/hooks/reanimated/useStableCallbackValue.ts
- packages/react-native-sortables/src/index.ts
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/index.ts
- packages/react-native-sortables/src/utils/order.ts
This PR fixed issue with invalid data array being passed to the drag end callback after adding recent worklet callbacks support feature.
> fix: Drag end callback invalid data array

- example/app/src/components/layout/Group.tsx
- example/app/src/components/layout/Section.tsx
- example/app/src/examples/SortableFlex/features/CallbacksExample.tsx
- example/app/src/examples/SortableGrid/features/CallbacksExample.tsx
Just a small fix for the in-app example
> fix: Data change example animated height conflicting with layout transition

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/config.yml
- packages/react-native-sortables/CHANGELOG.md
- packages/react-native-sortables/package.json
- yarn.lock
This PR introduces a custom issue template for better issue formats. It would be better for me to get detailed issue descriptions and easier for users to provide the necessary information.
> chore: Issue template

- packages/docs/docusaurus.config.ts
This PR adds algolia search functionality to docs for easier docs navigation.
> docs: Add algolia search functionality

- .github/ISSUE_TEMPLATE/bug_report.yml
Just a small change to allow selecting multiple devices where the issue occurs.
> chore: Allow selecting multiple devices in the issue template

- example/app/src/examples/SortableFlex/features/TouchableExample.tsx
- example/app/src/examples/SortableFlex/features/index.ts
- example/app/src/examples/SortableFlex/tests/ZeroDelayActivationTouchableExample.tsx
- example/app/src/examples/SortableFlex/tests/index.ts
- example/app/src/examples/SortableGrid/features/TouchableExample.tsx
- example/app/src/examples/SortableGrid/features/index.ts
- example/app/src/examples/navigation/routes.ts
- packages/react-native-sortables/CHANGELOG.md
- packages/react-native-sortables/src/components/shared/SortableTouchable.tsx
- packages/react-native-sortables/src/index.ts
This PR adds more callbacks to the `Sortable.Touchable` component:
- `onTap`: Callback function triggered when the item is tapped
- `onDoubleTap`: Callback function triggered when the item is double tapped
- `onLongPress`: Callback function triggered when the item is long pressed
- `onTouchesDown`: Callback function triggered when touches begin
- `onTouchesUp`: Callback function triggered when touches end
https://github.com/user-attachments/assets/4b4242bb-0446-4ca8-ada0-9655a37afae2
> feat: Add more touch events to the touchable

- packages/react-native-sortables/src/providers/shared/ItemContextProvider.ts
- packages/react-native-sortables/src/types/providers/shared.ts
- packages/react-native-sortables/src/types/utils.ts
This PR adds more useful values to the item context
> feat: Add keyToIndex and indexToKey to the item context

- packages/docs/docs/flex/props.mdx
- packages/docs/docs/grid/examples/touchable.mdx
- packages/docs/docs/grid/props.mdx
- packages/docs/docs/helper-components/touchable.mdx
- packages/docs/docs/hooks/useItemContext.mdx
- packages/react-native-sortables/src/components/shared/SortableTouchable.tsx
- packages/react-native-sortables/src/types/providers/shared.ts
- packages/react-native-sortables/src/types/utils.ts
This PR adds docs updates from the recent release of the library.
> docs: Add updates from the recent release

- example/app/src/examples/SortableGrid/PlaygroundExample.tsx
- packages/react-native-sortables/src/components/SortableFlex.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/index.ts
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/index.ts
- packages/react-native-sortables/src/providers/layout/grid/updates/common.ts
- packages/react-native-sortables/src/providers/shared/components/OrderUpdaterComponent.tsx
- packages/react-native-sortables/src/providers/shared/index.ts
- packages/react-native-sortables/src/types/props/flex.ts
- packages/react-native-sortables/src/types/props/grid.ts
- packages/react-native-sortables/src/types/providers/shared.ts
Just some cleanup and code improvements
> chore: Clean up order updaters and sort strategies management

- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/providers/SharedProvider.tsx
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemStyles.ts
- packages/react-native-sortables/src/providers/shared/index.ts
Small improvement for perf issues after #431
> perf: Reduce the number of unnecessary onLayout calls

- example/app/src/examples/SortableGrid/tests/InputFocusExample.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/constants/values.ts
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/index.ts
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/utils.ts
- packages/react-native-sortables/src/providers/layout/flex/utils/debug.ts
- packages/react-native-sortables/src/providers/layout/flex/utils/layout.ts
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/utils/layout.ts
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/CustomHandleProvider.ts
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/index.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemDecoration.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyle.ts
- packages/react-native-sortables/src/providers/shared/hooks/useTeleportedItemStyles.ts
- packages/react-native-sortables/src/types/layout/flex.ts
- packages/react-native-sortables/src/types/layout/grid.ts
- packages/react-native-sortables/src/types/layout/shared.ts
- packages/react-native-sortables/src/types/providers/shared.ts
- packages/react-native-sortables/src/utils/dimensions.ts
- packages/react-native-sortables/src/utils/equality.ts
> fix: Multiple minor improvements

- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/index.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemDecorationStyle.ts
- packages/react-native-sortables/src/types/providers/shared.ts
Moving some code executed in each cell to the common provider and some other cleanup of animated styles.
> chore: Optimize and clean up item cell animated styles

- .github/workflows/build-examples.yml
This PR adds CIs to check if all example apps build.
> feat: Add example app build check CIs

- packages/react-native-sortables/.releaserc
This PR adds more sections to auto generated release notes to better visually separate changes.
> chore: Add more sections in auto generated release notes

- .github/workflows/build-examples.yml
- .github/workflows/code_quality_checks.yml
- .github/workflows/rebase.yml
- .github/workflows/release.yml
- .github/workflows/unused-code-check.yml
- package.json
- yarn.lock
This PR bumps actions used in workflows to latest versions and optimizes workflows, which can be optimized, by adding concurrency.
> ci: Optimize workflows execution time and bump actions to latest
