- packages/docs/docs/flex/props.mdx
- packages/docs/docs/grid/props.mdx
This PR adds the `Animatable` helper type to docs for props that allow passing either a reanimated `SharedValue` or a static (plain) value.
This information was missing and types incorrectly indicated that only static values are supported.
> docs: Add Animatable type in prop definitions

- example/app/src/examples/SortableFlex/PlaygroundExample.tsx
- packages/react-native-sortables/src/components/shared/DropIndicator.tsx
- packages/react-native-sortables/src/constants/layout.ts
- packages/react-native-sortables/src/providers/layout/flex/utils/layout.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useItemPanGesture.ts
- packages/react-native-sortables/src/providers/shared/utils.ts
- packages/react-native-sortables/src/types/providers/shared.ts
This PR fixes:
- drop indicator position when other item started being touched before the drop animation of the previous touch target finished
|-|-|
| <video src="https://github.com/user-attachments/assets/b151648d-de19-4f1e-81ba-051d8412ba20" /> | <video src="https://github.com/user-attachments/assets/92b53086-9de6-40e9-a5b6-a952ef068bb5" /> |
---
- container overflow change when other item started being touched before the drop animation of the previous touch target finished
|-|-|
| <video src="https://github.com/user-attachments/assets/370a537b-0913-4608-bc24-a42ba8a6c2ba" /> | <video src="https://github.com/user-attachments/assets/b0a76cea-e6e3-4d52-a9c8-1aae711dcecc" /> |
---
- flex container height when only vertical padding was added (before, …
> fix: A bunch of small issues I noticed

- packages/react-native-sortables/src/components/shared/DraggableView.tsx
- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useItemTranslation.ts
- packages/react-native-sortables/src/types/providers/shared.ts
Small fix for the view drop animation on native after the `shouldAnimateLayout` prop was introduced to fix page resizing behavior on web. Before this change, the view appeared immediately on the target position if no reordering happened and the view was dragged without changing position from it initial render position.
> fix: View drop animation on native after adding shouldAnimateLayout

- packages/react-native-sortables/src/components/shared/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
This PR fixes issue with `animateHeight` not taking any effect after recent changes.
> fix: Animated sortable container height not working

- example/app/src/examples/SortableGrid/DragHandleExample.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/constants/props.ts
- packages/react-native-sortables/src/providers/SharedProvider.tsx
- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/flex/utils/layout.ts
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/updates/common.ts
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider.tsx
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.tsx
- packages/react-native-sortables/src/providers/shared/DragProvider.tsx
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useItemPanGesture.ts
- packages/react-native-sortables/src/providers/shared/hooks/useOrderUpdater.ts
- packages/react-native-sortables/src/types/props/shared.ts
- packages/react-native-sortables/src/types/providers/shared.ts
- packages/react-native-sortables/src/utils/reanimated/values.ts
This PR adds a new `allowOverDrag` property that clamps item position in such a way that it moves only within the sortable container and cannot be dragged outside of it.
This is useful e.g. for single-column grids when we want to limit item drag direction only to vertical.
| Web | Mobile |
|-|-|
| <video src="https://github.com/user-attachments/assets/64c04831-2f65-42f1-9297-6010b610ea60" /> | <video src="https://github.com/user-attachments/assets/21189525-58fe-436b-81bc-fa71af076c45" /> |
> feat: Possibility to disable container overflow by the dragged item

- example/app/src/examples/SortableFlex/FlexLayoutExample.tsx
- packages/react-native-sortables/src/providers/layout/flex/utils/layout.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.web.ts
This PR fixes:
- issues with multi column flex layout on web (when items wrap into multiple columns),
- problem with padding (I had to explicitly set `top`/`left` to 0 for absolute sortable grid items to ignore the container padding used only for the first, `relative` render),
- glitchy animation on the released item that was previously dragged on mobile (glitch happened when reordering animation started for some items after the active item release). Problem was caused by multiple `withTiming` assignments to `translateX` and `translateY`, when one overridden another (cancelling the previous one)
> fix: Web flex layout and mobile drop animation issues

- example/app/src/examples/SortableFlex/PlaygroundExample.tsx
- packages/react-native-sortables/src/utils/children.ts
This PR adds React Fragment components filtering out from the `Sortable.Flex` component children.
I used the following code to test if it works as expected.
<details>
<summary>Code snippet</summary>
```tsx
import { StyleSheet, Text, View } from 'react-native';
import Sortable from 'react-native-sortables';
import { ScrollScreen } from '@/components';
import { colors, text } from '@/theme';
import { getCategories, IS_WEB } from '@/utils';
const DATA = getCategories(IS_WEB ? 30 : 10);
export default function Flex() {
return (
<ScrollScreen>
<Sortable.Flex
gap={10}
padding={10}
onDragEnd={a => {
console.log('onDragEnd', a);
}}>
{/* You can render anything within the Sortable.Flex component */}
<>
<>
{DATA.map(item => (
<View key={item} style={styles.cell}>
<Text …
```
> fix: Sortable flex fragment children

- packages/react-native-sortables/src/providers/shared/DragProvider.tsx
This PR fixes drag activation with wrong initial position. This issue is caused by incorrect measurements being returned by the `measure` function from `react-native-reanimated` (only on the New Architecture, the Old Architecture works fine).
After changes, when the touch is outside of the activated item bounds, it will be simply ignored and the gesture will fail.
|-|-|
| <video src="https://github.com/user-attachments/assets/b7f96a6b-c8fd-4af7-ad84-100af48067b4" /> | <video src="https://github.com/user-attachments/assets/514b3033-f338-451d-98ec-687c4ad278c5" /> |
> fix: Invalid item activation on iOS Fabric after container scroll

- packages/docs/docs/flex/props.mdx
- packages/docs/docs/grid/props.mdx
- packages/react-native-sortables/src/components/shared/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/ItemDecoration.tsx
- packages/react-native-sortables/src/components/shared/SortableHandle.tsx
- packages/react-native-sortables/src/providers/shared/DragProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.web.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemPanGesture.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemZIndex.ts
- packages/react-native-sortables/src/types/providers/shared.ts
I use `LayoutAnimationConfig` to skip `itemEntering` and `itemExiting` animation from being applied when the entire sortable component renders or is unmounted. This is intentional but confusing, so I improved the description in docs to make it clear how these props are supposed to be used and how they work.
I also didn't unset `skipEntering` and `skipExiting` for views that the user renders within the sortable component, which is an invalid behavior preventing users from using any kind of `entering`/`exiting` reanimated layout animation. To fix this issue, I simply added another `LayoutAnimationConfig` that unsets `skipEntering` and `skipExiting` (sets them to `false`).
> fix: Don't skip entering and exiting animations on user's views, improve layout animations docs

- example/app/src/examples/SortableFlex/DragHandleExample.tsx
- example/app/src/examples/SortableGrid/DragHandleExample.tsx
- packages/react-native-sortables/src/components/SortableFlex.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/constants/props.ts
- packages/react-native-sortables/src/index.ts
- packages/react-native-sortables/src/providers/SharedProvider.tsx
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.tsx
- packages/react-native-sortables/src/providers/shared/DragProvider.tsx
- packages/react-native-sortables/src/providers/shared/components/OrderUpdaterComponent.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useOrderUpdater.ts
- packages/react-native-sortables/src/types/props/shared.ts
- packages/react-native-sortables/src/types/providers/shared.ts
This PR adds a possibility to customize the reorder trigger origin (i.e. the location of the point that will trigger order change).
It now makes it possible to choose between the `center` and the `touch` location and replaces the previous default `touch` location by the `center` location which seems more intuitive.
You can see the location of the `reorderTriggerOrigin` after enabling the debug mode with the `debug` property.
| `touch` (previous default) | `center` (current default) |
|-|-|
| <video src="https://github.com/user-attachments/assets/a6bb80da-f2d5-4413-9169-04e4e304c577" /> | <video src="https://github.com/user-attachments/assets/ec89614a-0821-4e23-8683-d9e42e44854f" /> |
> feat: Customizable reorder trigger origin

- example/app/src/components/items/GridCard.tsx
- example/app/src/examples/SortableGrid/features/HorizontalAutoScrollExample.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/providers/shared/DragProvider.tsx
Fixes problems described in the #291 issue
It also fixes broken grid card width after the RN upgrade (seems to be a RN style flattening issue).
|-|-|
| <video src="https://github.com/user-attachments/assets/c5e0a96a-2cdc-465c-a8e6-dae70b3054f0" /> | <video src="https://github.com/user-attachments/assets/5414a2a0-a6ec-40a3-aca3-520f0afacab9" /> |
> fix: Android crashes on gesture failure, horizontal scrollable issues

- packages/docs/docs/grid/props.mdx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/types/props/grid.ts
- packages/react-native-sortables/src/utils/keys.ts
Just a small fix for incorrect behavior when numeric values were passed. I incorrectly used the item index as a key, which caused layout flickering after items were reordred and rendered them in wrong positions.
> fix: Default keyExtractor behavior for numeric values

- packages/react-native-sortables/src/components/shared/createSortableTouchable.tsx
Fixes #306 
|-|-|
| <video src="https://github.com/user-attachments/assets/2957ce00-a85d-497a-9ea9-dee859a302b0" /> | <video src="https://github.com/user-attachments/assets/bbdd5de9-6fb9-4a7a-aa9b-0cda3a688255" /> |
<details>
<summary>Code snippet</summary>
```tsx
import { useMemo, useState } from 'react';
import { Button } from 'react-native';
import Sortable from 'react-native-sortables';
export default function BadGrid() {
const [isSelecting, setIsSelecting] = useState(false);
const data = useMemo(() => new Array(20).fill(0).map((_, i) => i), []);
console.log({ isSelecting });
const renderItem = () => (
<Sortable.TouchableOpacity
style={{ backgroundColor: 'red', height: 64, width: 64 }}
onPress={() => console.log('hello')}
/>
);
return (
<>
<Sortable.Grid
columns={3} …
```
> fix: onPress not working after disabling drag

- packages/react-native-sortables/src/providers/layout/flex/updates/insert/utils.ts
This PR fixed flex layout ordering logic that was incorrect. THe issue started to appear after changing the `reorderInsert` function in the #310 PR but was incorrectly implemented before.
> fix: Flex ordering after recent changes

- .eslintrc.cjs
- example/app/src/components/inputs/Button.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/debug/providers/DebugOutlet.tsx
- packages/react-native-sortables/src/debug/providers/DebugProvider.tsx
- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemDecorationStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.web.ts
- packages/react-native-sortables/src/types/debug.ts
- packages/react-native-sortables/src/types/providers/shared.ts
- packages/react-native-sortables/src/types/state.ts
This PR adds delayed absolute layout initialization when the `sortEnabled` prop os the sortable component is set to false. It reduces the number of calculations and applied animated styles to the minimum to make the initial render of the sortable component less demanding and calculates and applied the absolute layout only after the `sortEnabled` was set to `true` for the first time.
> feat: Delayed absolute layout initialization before sorting is enabled for the first time

- example/app/src/components/misc/ActionSheetDropdown.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
- packages/react-native-sortables/src/providers/shared/PortalOutletProvider.tsx
- packages/react-native-sortables/src/providers/shared/PortalProvider.tsx
It didn't work because the portal provider outlet was collapsed. Settings `collapsible` to false on the portal outlet and adding a few other changes fixes the issue.
> fix: Active portal not working on Android

- .eslintrc.cjs
- example/app/src/components/inputs/Switch.tsx
- example/app/src/examples/navigation/ExamplesStackNavigator.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/providers/shared/PortalProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/index.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemDecorationStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useTeleportedItemId.ts
- packages/react-native-sortables/src/providers/utils/createProvider.tsx
- packages/react-native-sortables/src/types/state.ts
This PR adds a possibility to easily enable/disable the active item portal provider via the `enabled` boolean prop on the `Sortable.PortalProvider` component. It also refactors the `DraggableView` component and some other helper components so that the smooth activation/deactivation of the portal is possible.
- **Before** - the entire components tree was unmounted and the new tree was mounted within or outside of the provider
- **After** - no unmounting/mounting happens, only a single re-render is needed
|-|-|
| <video src="https://github.com/user-attachments/assets/973074a7-1cb0-4a95-b82b-c7219c156cb4" /> | <video src="https://github.com/user-attachments/assets/38ff2dfa-75ec-445f-920d-f9eb9ebca19e" /> |
> feat: Add a possibility to enable or disable the portal provider

- packages/react-native-sortables/src/providers/layout/flex/utils/layout.ts
This PR fixes numeric precision issue resulting in incorrect `Sortable.Flex` items grouping. I added a small epsilon value to the inequality to make it work right.
|-|-|
| <video src="https://github.com/user-attachments/assets/283ccd4b-f172-4947-b704-6d5be7832b44" /> | <video src="https://github.com/user-attachments/assets/8cd80afa-3225-485d-939e-438d6c458a08" /> |
<details>
<summary>Source code</summary>
```tsx
import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import Animated, { useAnimatedRef } from 'react-native-reanimated';
import Sortable from 'react-native-sortables';
interface MenuItem {
id: string;
name: string;
}
// Initial data
const INITIAL_MENUS: Array<MenuItem> = [
{ id: 'menu-1', name: 'Dinner' },
{ id: …
```
> fix: Numeric precision error in flex grouping

- example/expo/package.json
- example/web/package.json
- yarn.lock
This PR bumps expo go example app to SDK 53 (preview, because stable hasn't been released yet). I decided to bump this example app as `react-native-reanimated` in version `3.16` had multiple issues and bumping it to `3.17` fixes them.
> chore: Bump expo go example app to next expo version

- example/app/src/examples/SortableGrid/features/DragHandleExample.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
This PR fixes 2 issues with column/row count in the sortable grid:
- Don't allow non-positive column/row count
- Fix invalid layout animation on android when column/row count changes
It also improves the column count change in the drag handle example - adds layout animation to grid card dimensions.
Example recording for column change on Android
|-|-|
| <video src="https://github.com/user-attachments/assets/a4a2e8fb-a46e-4726-817d-e9e636407348" /> | <video src="https://github.com/user-attachments/assets/5ef3c8d3-8eaa-4477-b0c4-2af63c2faca4" /> |
> fix: Column and row count issues

- packages/docs/docs/flex/props.mdx
- packages/docs/docs/grid/props.mdx
- packages/react-native-sortables/src/types/props/shared.ts
This PR:
- adds new `reorderTriggerOrigin` and `overflow` props to docs
- improves callbacks documentation and adds information about new feature - worklet callbacks
- Updates the type of `DropIndicatorComponentProps` in docs to the correct type
> docs: Documentation of some new props and features

- packages/react-native-sortables/src/providers/SharedProvider.tsx
- packages/react-native-sortables/src/providers/shared/ActiveItemValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/index.ts
- packages/react-native-sortables/src/providers/utils/createProvider.tsx
- packages/react-native-sortables/src/types/providers/shared.ts
This PR is just a preparation for the next one in which I will add support for item dragging between sortable components (like dragging from one grid to another). To implement this feature, I need to know the current position of the active item in all sortable components to detect when it enters another sortable component.
> chore: Move active item related values to a separate provider

- example/app/src/examples/SortableFlex/features/CallbacksExample.tsx
- example/app/src/examples/SortableGrid/features/CallbacksExample.tsx
- packages/react-native-sortables/src/constants/props.ts
- packages/react-native-sortables/src/index.ts
- packages/react-native-sortables/src/providers/SharedProvider.tsx
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/types/props/shared.ts
This PR adds more props to the `onDragStart` callback and implement the new `onActiveItemDropped` callback that is called when the active item drop animation finishes.
> feat: Active item dropped callback, more props in drag start callback

- packages/react-native-sortables/src/providers/shared/ItemContextProvider.ts
This PR fixes unnecessary re-renders when the item context is used within the sortable item context caused by the excessive data being passed to the context. I mistakenly put children in there, which usually change on each render.
> fix: Stop passing excessive data to the item context

- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
This PR removes invalid call to the gesture manager when the item gets removed before the gesture starts being handled.
> fix: Invalid call to gesture manager when item is no longer available

- packages/react-native-sortables/src/constants/platform.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemPanGesture.ts
This PR fixes multi touch flickering issue caused by the `handleDragEnd` being called on the cancelled gesture. The second touch gesture was properly ignored and failed but it called `handleDragEnd` as this method is always called in the `onFinalize` callback, which invalidated not only the second gesture that we wanted to ignore, but also the first one that was correct and should be still handled.
The behavior on Android is unfortunately not perfect, because when we start touching a second item, the gesture on the first one gets invalidated as the `onTouchesUp` callback is not properly called on the gesture instance. This is a `react-native-gesture-handler` issue that I reported here:
https://github.com/software-mansion/react-native-gesture-handler/issues/3543
> fix: Multi touch flickering issue

- example/app/package.json
- example/app/src/examples/SortableFlex/PlaygroundExample.tsx
- example/app/src/examples/SortableFlex/tests/BottomTabsNavigatorExample.tsx
- example/app/src/examples/SortableFlex/tests/index.ts
- example/app/src/examples/SortableGrid/index.ts
- example/app/src/examples/SortableGrid/tests/BottomTabsNavigatorExample.tsx
- example/app/src/examples/SortableGrid/tests/index.ts
- example/app/src/examples/navigation/routes.ts
- yarn.lock
This PR adds bottom tabs navigator example to test invalid content behavior on tab change.
> chore: Tab navigator example

- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.ts
- packages/react-native-sortables/src/types/providers/shared.ts
- packages/react-native-sortables/src/types/state.ts
This issue was caused by the optimization that delayed transition to absolute layout until `sortEnabled` is set to `true`. I remove this optimization as it shouldn't affect performance that much but added unnecessary complexity and introduced this issue.
> fix: Items not animated before `sortEnabled` is set to `true`

- packages/react-native-sortables/src/components/SortableFlex.tsx
It appears that reanimated's animated style might not override js style properties on web. To handle this case properly, we filter out flex props from the style that is passed to the sortable container and use them only in the animated style.
> fix: Flex layout with custom alignmnets on web

- packages/react-native-sortables/src/components/shared/AnimatedOnLayoutView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/providers/shared/PortalOutletProvider.tsx
- packages/react-native-sortables/src/providers/shared/PortalProvider.tsx
- packages/react-native-sortables/src/providers/shared/hooks/useItemDecorationStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useTeleportedItemStyles.ts
- packages/react-native-sortables/src/types/providers/shared.ts
Describe what was changed in this pull request
Include example images/recordings if the new feature introduces some
visual changes or the PR fixes a UI bug
> fix: Teleported active item flickering

- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/utils/layout.ts
- packages/react-native-sortables/src/providers/shared/hooks/index.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemDecorationValues.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemPosition.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemStyles.ts
- packages/react-native-sortables/src/providers/shared/hooks/useTeleportedItemPosition.ts
- packages/react-native-sortables/src/providers/shared/hooks/useTeleportedItemStyles.ts
- packages/react-native-sortables/src/utils/index.ts
- packages/react-native-sortables/src/utils/reanimated/index.ts
- packages/react-native-sortables/src/utils/reanimated/useMutableValue.ts
- packages/react-native-sortables/src/utils/styles.ts
This PR improves `ItemCell` component implementation by merging decoration animated styles and layout styles (which results in twice less animated views with custom props, so less commits and clones of ShadowNodes to apply reanimated changes). It also cleans up code a bit by separating item position calculation from animated styles hooks.
> perf: Merge item decoration styles with position styles

- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DropIndicator.tsx
- packages/react-native-sortables/src/hooks/reanimated/useStableCallbackValue.ts
- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/index.ts
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/updates/insert.ts
- packages/react-native-sortables/src/providers/layout/grid/updates/swap.ts
- packages/react-native-sortables/src/providers/shared/ActiveItemValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/hooks.ts
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/index.tsx
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/CustomHandleProvider.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/providers/shared/LayerProvider.tsx
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/providers/shared/PortalOutletProvider.tsx
- packages/react-native-sortables/src/providers/shared/PortalProvider.tsx
- packages/react-native-sortables/src/utils/reanimated/useAnimatedDebounce.ts
- packages/react-native-sortables/src/utils/reanimated/useMutableValue.ts
This PR replaces all `useSharedValue` usages with `useMutableValue`. `useSharedValue` is heavier because of the cleanup `useEffect` that cancels currently running animation if there is any:
```
export function useSharedValue<Value>(initialValue: Value): SharedValue<Value> {
const [mutable] = useState(() => makeMutable(initialValue));
useEffect(() => {
return () => {
cancelAnimation(mutable);
};
}, [mutable]);
return mutable;
}
```
I don't need this behavior as I never use infinite animations and, in most cases, don't use animations at all, rather update value by myself. I only use animations for items reordering and the drop indicator, but since they are just short `withTiming` animations, the cleanup is not necessary. Even if the animation keeps running after the view was unmounted, it …
> perf: Replace useSharedValue with useMutableValue

- packages/react-native-sortables/src/constants/props.ts
- packages/react-native-sortables/src/providers/SharedProvider.tsx
- packages/react-native-sortables/src/types/props/grid.ts
- packages/react-native-sortables/src/types/props/shared.ts
This PR should fix the context menu issue reported in #417. The issue seems to be caused by the `zIndex` change of the sortable component when the item gets activated, which cancels the long press gesture from the context menu. I haven't found any better solution than this, which lets the user disable the `zIndex` change and just added a new prop to disable it.
Setting `bringToFrontWhenActive` to `false`, unfortunately results in rendering sortable items below its siblings rendered below (after it), which can be seen in the following example.
<details>
<summary>Source code</summary>
```tsx
import { useCallback } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import type { SortableGridRenderItem } from 'react-native-sortables';
import Sortable from …
```
> fix: Allow disabling default layer provider

- example/app/src/examples/SortableGrid/PlaygroundExample.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/constants/platform.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemStyles.ts
This PR fixes invalid `ScrollView` behavior when the `TextInput` component was focused. I noticed that this is caused by the fact that all items rendered within the sortable component use transforms for positioning (as transforms are said to be faster than `top`/`left` props). 
Unfortunately, the position of the `ScrollView` is adjusted based on the render position of the `TextInput` component but in our case all items are rendered in the top left corner of the sortable component container and then transformed to their proper positions on the screen.
I decided to replace transforms with `top` and `left` layout props which seem to work fine.
|-|-|
| <video src="https://github.com/user-attachments/assets/83168a03-3216-43d2-b49b-b603b5e332c0" /> | <video …
> fix: Invalid ScrollView position on input focus

- example/app/src/examples/navigation/routes.ts
- packages/react-native-sortables/src/components/SortableFlex.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/components/shared/DropIndicator.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/providers/SharedProvider.tsx
- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/index.ts
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/utils.ts
- packages/react-native-sortables/src/providers/layout/flex/utils/debug.ts
- packages/react-native-sortables/src/providers/layout/flex/utils/layout.ts
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/utils/layout.ts
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/index.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemDimensions.ts
- packages/react-native-sortables/src/providers/shared/hooks/useTeleportedItemStyles.ts
- packages/react-native-sortables/src/providers/shared/index.ts
- packages/react-native-sortables/src/providers/shared/utils.ts
- packages/react-native-sortables/src/types/layout/flex.ts
- packages/react-native-sortables/src/types/layout/grid.ts
- packages/react-native-sortables/src/types/providers/shared.ts
- packages/react-native-sortables/src/utils/dimensions.ts
- packages/react-native-sortables/src/utils/equality.ts
- packages/react-native-sortables/src/utils/index.ts
This PR separates controlled item dimensions from uncontrolled ones, updated when item sizes change. This change is especially useful on web, when the size of items (e.g. the width of grid columns) can change when the window is resized. In this case, we don't want to update measured dimensions for all items separately and instead it is better to use the already known column width.
> feat: Separate controlled item dimensions from measured dimensions

- packages/react-native-sortables/src/constants/platform.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemStyles.ts
This PR implements more performant items reordering in sortable components that takes architectural differences into account (the `onLayout` callback is called more often on the New Architecture if we use layout-based items positioning).
> perf: More performant items reordering

- example/app/src/examples/SortableGrid/features/DragHandleExample.tsx
- example/fabric/ios/Podfile.lock
- example/fabric/metro.config.js
- example/paper/ios/Podfile.lock
- example/paper/metro.config.js
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayoutStyle.ts
- packages/react-native-sortables/src/types/providers/shared.ts
Describe what was changed in this pull request
Videos were recorded on Paper but on Fabric the improvement looks even better
|-|-|
| <video src="https://github.com/user-attachments/assets/94c7cc3b-0d71-4bad-aae5-4e292523d550" /> | <video src="https://github.com/user-attachments/assets/b9ef1a76-b0ea-4d1a-8c8d-05bee9cf2d06" /> |
> feat: Make layout update in sync with positions change on grid columns change

- packages/react-native-sortables/src/providers/layout/flex/FlexLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/flex/updates/insert/index.ts
- packages/react-native-sortables/src/providers/layout/grid/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/layout/grid/updates/common.ts
- packages/react-native-sortables/src/types/layout/flex.ts
- packages/react-native-sortables/src/types/providers/layout.ts
This PR simplifies layout calculation logic for grid and flex components. It also optimizes the main layout calculation reaction which was previously improperly auto-workletized and ran sometimes 3 times instead of just once per layout change.
> perf: Reduce the number of layout calculations

- packages/react-native-sortables/src/constants/layoutAnimations.ts
- packages/react-native-sortables/src/integrations/reanimated/utils/animatedTimeout.ts
- packages/react-native-sortables/src/providers/flex/layout/updates/insert/utils.ts
- packages/react-native-sortables/src/providers/flex/layout/utils/layout.ts
- packages/react-native-sortables/src/providers/grid/layout/utils/helpers.ts
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/utils.ts
- packages/react-native-sortables/src/providers/shared/utils.ts
- packages/react-native-sortables/src/utils/arrays.ts
- packages/react-native-sortables/src/utils/dimensions.ts
- packages/react-native-sortables/src/utils/equality.ts
- packages/react-native-sortables/src/utils/layout.ts
- packages/react-native-sortables/src/utils/logs.ts
- packages/react-native-sortables/src/utils/misc.ts
- packages/react-native-sortables/src/utils/operations.ts
This PR moves the `'worklet'` directive to the top of the file where possible (in files which contain only worklet functions).
> chore: Clean up worklet directive usage

- packages/react-native-sortables/src/providers/shared/DragProvider.ts
The `onActiveItemDropped` callback was not fired when the item was touched again quickly after being released. We don't need to cancel this timeout so I just removed the timeout handle to make it work.
> fix: onActiveItemDropped not being fired when item is touched quickly

- packages/react-native-sortables/src/helperTypes.ts
- packages/react-native-sortables/src/types/debug.ts
- packages/react-native-sortables/src/types/props/grid.ts
This PR adds a complex helper generic type to simplify creation of unions having the same props but some of props marked as `never`. It also makes horizontal grid types more strict and no longer allows mixing horizontal grid props with vertical grid props.
I know that the type error message could be better but this is the best what I can do
> chore: Simplify unions with excluded props

- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
- packages/react-native-sortables/src/integrations/reanimated/utils/animatedTimeout.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
This PR fixes 2 issues related to collapsible items:
1. Incorrect position of the item when the drag starts
2. No dimensions layout transition of the active item when teleported (was rendered with the new dimensions right away)
> fix: Incorrect drag start position, no item size animation when teleported

- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/providers/grid/GridLayoutProvider/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/grid/GridLayoutProvider/updates/common.ts
- packages/react-native-sortables/src/providers/shared/MeasurementsProvider.ts
- packages/react-native-sortables/src/types/providers/grid.ts
The `resetMeasurements` method was called in the `useEffect` on the first render, which cleared all item measurements before the layout was calculated. As a result, we got weird content stretch when the item started being dragged.
> fix: Invalid grid layout on mount

- example/app/src/examples/SortableGrid/miscellaneous/CollapsibleItemsExample.tsx
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
This issue was caused by incorrect `measure` function output on Android (the same incorrect output is returned by the Reanimated's and RN's implementation). This was best visible after scrolling a bit in the collapsible items example, pressing the item once and pressing it again without changing the scroll position. At the second press, the container's `pageY` position was completely wrong, causing the active item to fly away far from the user's finger.
As a workaround, I decided to calculate the item's position in the container's position independent way.
> fix: Active item touch start position on Android

- example/app/src/examples/SortableGrid/features/DataChangeExample.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ActiveItemPortal.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/DraggableView.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/ItemCell.tsx
- packages/react-native-sortables/src/components/shared/DraggableView/TeleportedItemCell.tsx
- packages/react-native-sortables/src/providers/grid/GridLayoutProvider/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/AutoScrollProvider.tsx
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/utils.ts
- packages/react-native-sortables/src/providers/shared/CommonValuesProvider.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/index.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemDecoration.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemLayout.ts
- packages/react-native-sortables/src/providers/shared/hooks/useTeleportedItemLayout.ts
- packages/react-native-sortables/src/types/providers/shared.ts
> fix: A bunch of issues, like shaky scroll, invalid grid layout, added items flickering

- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/AutoScrollProvider.tsx
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/utils.ts
This PR fixes the issue caused by the fact that `measure` sometimes returns slightly outdated values, thus the container scroll offset was invalid and we were scrolling beyond the bounds of the scrollable content size.
To fix the issue, I decided to check whether the new `contentOffset` is different from the old one before calling the `scrollBy` function in order not to queue too many scroll updates, which can sum up to the invalid distance outside of the scrollable content container size.
> fix: Autoscroll exceeding bounds

- packages/react-native-sortables/bob.config.cjs
It seems that the `react-native-builder-bob` no longer accepts an array of excludes after the upgrade and it must be passed a single string now.
> fix: Invalid builder bob config

- example/app/src/examples/SortableGrid/features/AutoScrollExample.tsx
- packages/react-native-sortables/src/components/SortableFlex.tsx
- packages/react-native-sortables/src/components/SortableGrid.tsx
- packages/react-native-sortables/src/components/shared/SortableContainer.tsx
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/AutoScrollProvider.tsx
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/useDebugHelpers.ts
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/utils.ts
- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/types/providers/shared.ts
This PR is an another fix to the issue that I attempted to fix in the #473 PR. It seems that the issue still occurred as the `measure` function and the `scrollOffset` value received from the `useScrollOffset` weren't updated in sync.
> fix: Prevent auto scroll from over scrolling content container

- example/app/src/examples/SortableGrid/miscellaneous/CollapsibleItemsExample.tsx
- example/app/src/examples/navigation/routes.ts
- packages/react-native-sortables/src/providers/grid/GridLayoutProvider/GridLayoutProvider.tsx
- packages/react-native-sortables/src/providers/shared/AutoScrollProvider/AutoScrollProvider.tsx
This PR adjusts the example and the grid layout provider to work properly with on the web.
> fix: Collapsible items implementation on the web

- example/expo/package.json
- example/web/package.json
- yarn.lock
This PR fixes the `expo` package version in `package.json` files to prevent the `expo-doctor` from complaining.
> ci: Expo app build CI failure caused by expo-doctor

- .github/workflows/build-examples.yml
There was an issue with the group name which immediately cancelled example app builds
> ci: Fix concurrency group in react native example app build

- packages/react-native-sortables/src/providers/shared/DragProvider.ts
- packages/react-native-sortables/src/providers/shared/hooks/useItemPanGesture.ts
For some reason the `onFinalize` method is no longer called on the gesture detector when the manual gesture manager's `end` method is called. I moved the `handleDragEnd` call to the `onTouchesUp` and `onTouchesCancelled` methods to call it directly without relying on the `onFinalize` callback.
> fix: Active item getting stuck on iOS 26
